// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetDemo.Models;

namespace NetDemo.Models.Migrations
{
    [DbContext(typeof(demoContext))]
    [Migration("20190821180116_AddedProperties2PersonAndTraining")]
    partial class AddedProperties2PersonAndTraining
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetDemo.Models.Person", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Age");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<string>("SecurityToken");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("NetDemo.Models.Training", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Desc");

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<int?>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("NetDemo.Models.Training", b =>
                {
                    b.HasOne("NetDemo.Models.Person", "Person")
                        .WithMany("Training")
                        .HasForeignKey("PersonId")
                        .HasConstraintName("FK_Training_Person");
                });
#pragma warning restore 612, 618
        }
    }
}
